---
- hosts: webservers
  gather_facts: no
  become: yes
  tasks:
    - name: Display start message
      debug:
        msg: "********************************************************************************"
    
    - name: Display start time
      command: date
      register: start_time
      changed_when: false
      ignore_errors: yes

    - name: Display starting message
      debug:
        msg: "Starting at : {{ start_time.stdout }}"
    
    - name: Display end message
      debug:
        msg: "********************************************************************************"
    
    - name: Define PROJECT_SEARCH_DOMAIN variable
      set_fact:
        PROJECT_SEARCH_DOMAIN: "search c.gcp-keng01.internal. google.internal. c.gcp-keng01.internal int.dev.mykronos.com"
    
    - name: Define PROJECT_NAMESERVERS variable
      set_fact:
        PROJECT_NAMESERVERS: "nameserver 10.3.16.88"
    
    - name: Ensure resolv.conf.tmp contains specified lines
      ansible.builtin.lineinfile:
        path: /tmp/resolv.conf.tmp
        line: "{{ item }}"
        create: yes
      with_items:
        - '# Generated by NetworkManager'
        - '{{ PROJECT_SEARCH_DOMAIN }}'
        - '{{ PROJECT_NAMESERVERS }}'
    
    - name: Replace semicolons with newlines in /tmp/resolv.conf.tmp
      ansible.builtin.replace:
        path: /tmp/resolv.conf.tmp
        regexp: ';'
        replace: '\n'

    - name: Creating an empty file
      file:
        path: "/etc/resolv.conf"
        state: touch
        
    - name: Copy /tmp/resolv.conf.tmp to /etc/resolv.conf
      ansible.builtin.copy:
        src: /tmp/resolv.conf.tmp
        dest: /etc/resolv.conf
    
    - name: Print message
      ansible.builtin.debug:
        msg: "Updated /etc/resolv.conf"

    - name: Read the contents of /etc/resolv.conf
      ansible.builtin.shell:
        cmd: cat /etc/resolv.conf
      register: resolv_conf_content

    - name: Display the contents of /etc/resolv.conf
      ansible.builtin.debug:
        var: resolv_conf_content.stdout_lines

    - name: Print a line of hashes
      ansible.builtin.debug:
        msg: "################################################################################"

    - name: Display end message
      ansible.builtin.debug:
        msg: "Finishing Execution - Overwrite_Resolv_Conf"
    
    - name: Display end time
      command: date
      register: end_time
      changed_when: false
      ignore_errors: yes

    - name: Display finishing message
      debug:
        msg: "Finishing at : {{ end_time.stdout }}"
    
    - name: Display end message
      debug:
        msg: "################################################################################"
