---
# -----------------------------------------------------------------------------
#
#  Overwrites /etc/resolv.conf with good DNS entries.  This ensures we have
#  proper DNS.  NetworkManager has a tendency to overwrite this file with
#  its own values which don't work for us.
#
# -----------------------------------------------------------------------------
- name: Set permissions for id_rsa
  hosts: localhost  
  tasks:
    - name: Set permissions
      command: chmod 600 ./id_rsa
      
- hosts: webservers
  gather_facts: no
  become: yes
  tasks:
    - name: Display start message
      ansible.builtin.debug:
        msg: "Starting Execution - Overwrite_Resolv_Conf"
    
    - name: Start time
      command: date
      register: start_time
      changed_when: false
      ignore_errors: yes

    - name: Display starting message
      ansible.builtin.debug:
        msg: "Starting at : {{ start_time.stdout }}"

    - name: Define PROJECT_SEARCH_DOMAIN variable
      set_fact:
        PROJECT_SEARCH_DOMAIN: "search 1us-west4-a.c.ksp-gcp-58608.internal 1c.ksp-gcp-58608.internal 1google.internal"
    
    - name: Define PROJECT_NAMESERVERS variable
      set_fact:
        PROJECT_NAMESERVERS: "nameserver 128.0.0.53"
    
    - name: Ensure resolv.conf.tmp contains specified lines
      ansible.builtin.lineinfile:
        path: /tmp/resolv.conf.tmp
        line: "{{ item }}"
        create: yes
      with_items:
        - '# Generated by NetworkManager'
        - '{{ PROJECT_SEARCH_DOMAIN }}'
        - '{{ PROJECT_NAMESERVERS }}'
    
    - name: Replace semicolons with newlines in /tmp/resolv.conf.tmp
      ansible.builtin.replace:
        path: /tmp/resolv.conf.tmp
        regexp: ';'
        replace: '\n'

    - name: Read the contents of /tmp/resolv.conf.tmp
      ansible.builtin.shell:
        cmd: cat /tmp/resolv.conf.tmp
      register: resolv_conf_tmp_content

    - name: Display the contents of /tmp/resolv.conf.tmp
      ansible.builtin.debug:
        var: resolv_conf_tmp_content.stdout_lines

    - name: Copy /tmp/resolv.conf.tmp to /etc/resolv.conf
      ansible.builtin.copy:
        src: /tmp/resolv.conf.tmp
        dest: /etc/resolv.conf
    
    - name: Print message
      ansible.builtin.debug:
        msg: "Updated /etc/resolv.conf"

    - name: Read the contents of /etc/resolv.conf
      ansible.builtin.shell:
        cmd: cat /etc/resolv.conf
      register: resolv_conf_content

    - name: Display the contents of /etc/resolv.conf
      ansible.builtin.debug:
        var: resolv_conf_content.stdout_lines

    - name: Display end message
      ansible.builtin.debug:
        msg: "Finishing Execution - Overwrite_Resolv_Conf"
    
    - name: Display end time
      command: date
      register: end_time
      changed_when: false
      ignore_errors: yes

    - name: Display finishing message
      ansible.builtin.debug:
        msg: "Finishing at : {{ end_time.stdout }}"
